"use strict";

exports.__esModule = true;
exports.WEBZ_IO = exports.THE_NEWS_API = exports.STACK_OVERFLOW = exports.REDDIT = exports.NEWS_API_LONG = exports.NEWS_API = exports.MESSARI = exports.IEX_CLOUD = exports.FMP_LONG = exports.FMP = exports.DEV_TO = exports.CRYPTO_COMPARE = exports.COIN_STATS = exports.ALPHA_VANTAGE = void 0;
var CRYPTO_COMPARE = 'CryptoCompare';
exports.CRYPTO_COMPARE = CRYPTO_COMPARE;
var COIN_STATS = 'CoinStats';
exports.COIN_STATS = COIN_STATS;
var MESSARI = 'Messari';
exports.MESSARI = MESSARI;
var IEX_CLOUD = 'IEX Cloud';
exports.IEX_CLOUD = IEX_CLOUD;
var FMP = 'FMP';
exports.FMP = FMP;
var FMP_LONG = 'Financial Modeling Prep';
exports.FMP_LONG = FMP_LONG;
var ALPHA_VANTAGE = 'Alpha Vantage';
exports.ALPHA_VANTAGE = ALPHA_VANTAGE;
var NEWS_API = 'NewsApi';
exports.NEWS_API = NEWS_API;
var NEWS_API_LONG = 'NewsApi.org';
exports.NEWS_API_LONG = NEWS_API_LONG;
var THE_NEWS_API = 'TheNewsAPI';
exports.THE_NEWS_API = THE_NEWS_API;
var WEBZ_IO = 'Webz.io';
exports.WEBZ_IO = WEBZ_IO;
var REDDIT = 'Reddit';
exports.REDDIT = REDDIT;
var DEV_TO = 'Dev To';
exports.DEV_TO = DEV_TO;
var STACK_OVERFLOW = 'StackOverflow';
exports.STACK_OVERFLOW = STACK_OVERFLOW;
//# sourceMappingURL=ProviderNames.js.map