"use strict";

exports.__esModule = true;
exports.WEBZ_IO = exports.THE_NEWS_API = exports.STACK_OVERFLOW = exports.REDDIT = exports.NEWS_API_LONG = exports.NEWS_API = exports.MESSARI = exports.IEX_CLOUD = exports.FMP_LONG = exports.FMP = exports.DEV_TO = exports.CRYPTO_COMPARE = exports.COIN_STATS = exports.ALPHA_VANTAGE = void 0;
const CRYPTO_COMPARE = 'CryptoCompare';
exports.CRYPTO_COMPARE = CRYPTO_COMPARE;
const COIN_STATS = 'CoinStats';
exports.COIN_STATS = COIN_STATS;
const MESSARI = 'Messari';
exports.MESSARI = MESSARI;
const IEX_CLOUD = 'IEX Cloud';
exports.IEX_CLOUD = IEX_CLOUD;
const FMP = 'FMP';
exports.FMP = FMP;
const FMP_LONG = 'Financial Modeling Prep';
exports.FMP_LONG = FMP_LONG;
const ALPHA_VANTAGE = 'Alpha Vantage';
exports.ALPHA_VANTAGE = ALPHA_VANTAGE;
const NEWS_API = 'NewsApi';
exports.NEWS_API = NEWS_API;
const NEWS_API_LONG = 'NewsApi.org';
exports.NEWS_API_LONG = NEWS_API_LONG;
const THE_NEWS_API = 'TheNewsAPI';
exports.THE_NEWS_API = THE_NEWS_API;
const WEBZ_IO = 'Webz.io';
exports.WEBZ_IO = WEBZ_IO;
const REDDIT = 'Reddit';
exports.REDDIT = REDDIT;
const DEV_TO = 'DEV Community';
exports.DEV_TO = DEV_TO;
const STACK_OVERFLOW = 'StackOverflow';
exports.STACK_OVERFLOW = STACK_OVERFLOW;
//# sourceMappingURL=ProviderNames.js.map